name: amor_app
description: Notre histoire ❤️
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # <<--- Firebase --->
  firebase_core: ^3.0.0
  cloud_firestore: ^5.0.0
  firebase_messaging: ^15.2.0

  # <<--- State Management --->
  provider: ^6.1.2

  # <<--- Navigation --->
  go_router: ^14.0.0

  # <<--- UI --->
  cached_network_image: ^3.3.1
  google_fonts: ^6.2.1

  # <<--- Stockage local --->
  shared_preferences: ^2.2.3

  # <<--- Capteurs (shake) --->
  sensors_plus: ^5.0.0

  # <<--- Réseau --->
  http: ^1.2.1

  # <<--- Icônes --->
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  flutter_dotenv: ^6.0.1
  firebase_storage: ^12.4.10
  image_picker: ^1.2.2
  flutter_image_compress: ^2.4.0
  path: ^1.9.1
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.1

  # <<--- Tests unitaires (mocks sans génération de code) --->
  mocktail: ^1.0.4

  # <<--- Firestore factice pour tester le mapping DocumentSnapshot --->
  fake_cloud_firestore: ^3.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/amorapp.png"
  min_sdk_android: 21
  adaptive_icon_background: "#F88379"  # couleur de fond si besoin
  adaptive_icon_foreground: "assets/images/amorapp.png"
